//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeCenterEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.GradeBreakdowns = new HashSet<GradeBreakdown>();
            this.GradeTypes = new HashSet<GradeType>();
        }
    
        public int CourseId { get; set; }
        public int StudentId { get; set; }
        public string CourseName { get; set; }
        public int Year { get; set; }
        public int SemesterID { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<GradeBreakdown> GradeBreakdowns { get; set; }
        public virtual ICollection<GradeType> GradeTypes { get; set; }
    }
}
