//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeType
    {
        public GradeType()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int GradeTypeId { get; set; }
        public string GradeTypeName { get; set; }
        public int CourseId { get; set; }
        public int GradeWeight { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
