//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeId { get; set; }
        public int GradeTypeId { get; set; }
        public int Grade1 { get; set; }
    
        public virtual GradeType GradeType { get; set; }
    }
}
